### ISSUE TITLE
ダミーデータの作成

### ISSUE THREAD

**Issue by Kimtaewon9483** [Kimtaewon9483/pj-suju-front#11]
下さん担当のページのデータと、スケジュールに入る予定のデータを用意して欲しいです。

@shimo-web  (Blog)
下さんのページで欲しいデータの記入お願いいたします。
例
{
 postId: 0,
 userId: '',
 title: '',
 ...
 など
}

@Kimtaewon9483 　（スケジュール）
{
 userId: '',
 title: '',
 location: '',
 content: '',
 start_date: '2023-01-01',
 end_date: '2023-12-31',
}

上記のようなデータお願い致します。

**Comment by shimo-web** [comment]
{
  "posts": [
    {
      "id": "1",
      "title": "create-react-app直後にやる環境構築の備忘録",
      "createdAt": 1620804168398,
      "updatedAt": 1621064460898,
      "body": "本文テキスト1",
      "image": "/assets/images/dummy01.jpeg",
      "like": 100,
      "publish": false
    },
    {
      "id": "2",
      "title": "Reactを使ったお天気アプリを作成してみた",
      "createdAt": 1620804168398,
      "updatedAt": 1621070951011,
      "body": "本文テキスト2",
      "image": "/assets/images/dummy01.jpeg",
      "like": 112,
      "publish": true
    }
  ]
}
はい

**Comment by shimo-web** [comment]
title
content
auther?userld?
timestamp
comment
blogだとぐらいですかね？
